"""add model monitoring and evaluations

Revision ID: 0e37df485cad
Revises: 918faf412ed3
Create Date: 2026-09-29 11:13:41.485382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e37df485cad'
down_revision = '918faf412ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_datasets_owner_id'), ['owner_id'], unique=False)

    op.create_table('evaluation_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_cases_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('output_chars', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_call_logs_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_call_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_call_logs_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_call_logs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_model_call_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_call_logs_app_id'))

    op.drop_table('model_call_logs')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('evaluation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_cases_dataset_id'))

    op.drop_table('evaluation_cases')
    with op.batch_alter_table('evaluation_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_datasets_owner_id'))

    op.drop_table('evaluation_datasets')
    # ### end Alembic commands ###
