"""add encrypted model providers

Revision ID: 3a72c44fb712
Revises: f6ef4c1d8730
Create Date: 2026-09-29 10:57:53.596109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72c44fb712'
down_revision = 'f6ef4c1d8730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_providers_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_providers_owner_id'))

    op.drop_table('model_providers')
    # ### end Alembic commands ###
