"""bind apps and versions to model providers

Revision ID: 724072298a61
Revises: 3a72c44fb712
Create Date: 2026-09-29 10:59:28.055250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724072298a61'
down_revision = '3a72c44fb712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_app_versions_provider_id', 'model_providers', ['provider_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_apps_provider_id'), ['provider_id'], unique=False)
        batch_op.create_foreign_key('fk_apps_provider_id', 'model_providers', ['provider_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_apps_provider_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_apps_provider_id'))
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_app_versions_provider_id', type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
