"""add immutable app versions

Revision ID: f6ef4c1d8730
Revises: 57bd734b0ae6
Create Date: 2026-09-29 10:55:40.487958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ef4c1d8730'
down_revision = '57bd734b0ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'version', name='uq_app_version')
    )
    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_versions_app_id'), ['app_id'], unique=False)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('published_version')

    with op.batch_alter_table('app_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_versions_app_id'))

    op.drop_table('app_versions')
    # ### end Alembic commands ###
